### PR TITLE
Update tox.ini for coveralls compatibility with tox 2.0

### PR DESCRIPTION
**Pull request by cmeeren**
See coagulant/coveralls-python#73 and referenced issues/PRs. This fixed the issue for me.

### CODE REVIEW

**Comment by ionelmc** [comment]
Good catch!

I'm also considering having a `passenv = *` - there are many other cases [1] that break because of missing env vars.

[1] 
  https://bitbucket.org/hpk42/tox/issue/248/pass-through-vs-comntools-during-install
  https://bitbucket.org/hpk42/tox/issue/254/tox-2-fails-with-unicodedecodeerror-trying
  https://bitbucket.org/hpk42/tox/issue/253/newer-tox-prevents-usage-of-ssh-agent-201

**Comment by cmeeren** [comment]
Good idea, I don't see any reason not to do that (that's how it used to work, after all). Will that need to be added in each ``[testenv:foo]`` or is it in effect for all the environments if it is added to ``[testenv]``?

**Comment by ionelmc** [comment]
Adding it in `[testenv]` is sufficient.

**Comment by cmeeren** [comment]
Ok. Will you do that yourself or should I modify my PR? Or haven't you decided yet?

**Comment by ionelmc** [comment]
You can make the change if you want. I'll all some info in the readme about why we allow all vars after that.

**Comment by ionelmc** [comment]
Alright, thanks.

**Pull request merged**
