### PR TITLE
Use readthedocs sphinx theme

### PR DESCRIPTION
**Pull request by cmeeren**
Since you already have the readthedocs badge in the readme, I assume it is desirable to use the readthedocs theme locally too see how it will turn out before pushing. The whole ``on_rtd`` business is [a documented fix](https://docs.readthedocs.org/en/latest/theme.html#how-do-i-use-this-locally-and-on-read-the-docs).

### CODE REVIEW

**Comment by ionelmc** [comment]
The theme in there is something custom, not the RTD theme. It looks like http://python-aspectlib.readthedocs.org/en/latest/

I can see that there's appeal to just use RTD's theme by default. Maybe we should have some comments around for instructions on how to use a custom theme?

**Comment by cmeeren** [comment]
That, or a question "use RTD doc theme?" when running cookiecutter.

**Comment by ionelmc** [comment]
Yes, that would be better :-)

**Comment by cmeeren** [comment]
I'll leave that up to you then, I have no knowledge of cookiecutter's internals or jinja :)

**Comment by ionelmc** [comment]
Actually it's not that hard, eg: https://github.com/ionelmc/cookiecutter-pylibrary/commit/ddcb4136319e6f38e60aaa4f23231d5e3e1d6048

**Comment by ionelmc** [comment]
Give it a shot :grin:

**Pull request closed without merging**
