### PR TITLE
Add `test_runner` option with two possible values: pytest and nosetests.

### PR DESCRIPTION
**Pull request by svetlyak40wt**

### CODE REVIEW

**Comment by ionelmc** [comment]
You need to add `nose` to the dependencies (and the coverage plugin maybe?).

**Comment by svetlyak40wt** [comment]
Good catch! Forgot them.

**Comment by ionelmc** [comment]
I think I forgot to mention the help section in the readme: https://github.com/ionelmc/cookiecutter-pylibrary/blob/master/README.rst#usage - there should be row about the `test_runner` variable.

One more thing: I wonder if the option name for `nosetests` shouldn't be just `nose`. What do you think?

**Comment by ionelmc** [comment]
Look good. I've pushed it to the develop branch. Gonna push it to master after some testing, seems appveyor is useless.

**Comment by svetlyak40wt** [comment]
Ok, thank you!

**Pull request closed without merging**
