### PR TITLE
Add support for setup.py tests_require

### PR DESCRIPTION
**Pull request by techdragon**
- Add the tests_require field to setup.py

### CODE REVIEW

**Comment by ionelmc** [comment]
Hmmm, where is this useful? People who run `setup.py test`? Wouldn't that need something like https://pypi.python.org/pypi/pytest-runner?

**Comment by techdragon** [comment]
Ideally, I'd like to see Tox use the setup.py test_requires to add any additional test dependencies automatically when building the tox environments, instead of having to add them to the tox environment configuration. This would reduce some duplication of configuration information in the overall project structure. 

IDE's like PyCharm can use this particular setting in setup.py to ensure that a working environment or virtualenv, has the packages necessary to run the tests and help correctly configure a debugging environment. While they are not able to do the same to packages added into the Tox configuration options.

**Comment by techdragon** [comment]
@ionelmc #122 added `setup_requires` not `tests_require` so that PR has not actually closed this one.

**Comment by ionelmc** [comment]
@techdragon that PR aliases `setup.py test` to a different command provided by pytest-runner. Isn't that enough?

**Pull request closed without merging**
