### PR TITLE
Fix sphinx rendering if no parameter description

### PR DESCRIPTION
**Pull request by cmeeren**
See sphinx-doc/sphinx#2135

### CODE REVIEW

**Comment by ionelmc** [comment]
Can you add some spaces around that assignment? :grin:

**Comment by cmeeren** [comment]
Oh, right. Want me to do the two assignments above too?

**Comment by ionelmc** [comment]
Yes

**Comment by cmeeren** [comment]
Spaces all around! You're welcome :grin:

**Comment by ionelmc** [comment]
Yay!

**Pull request merged**
