### PR TITLE
A smaller implementation of #139 with a single file.

### PR DESCRIPTION
**Pull request by ionelmc**
@dHannasch so this is what I had in mind. From what I understand you have extremely lean system with no tooling like virtualenv/tox available on $PATH - this should solve without having extra files around.

### CODE REVIEW

**Comment by dHannasch** [comment]
This is basically the same as the argparse mockup in https://github.com/ionelmc/cookiecutter-pylibrary/pull/139#issuecomment-534244647, right?
```
if __name__ == "__main__":
    argparse...
    if args.definitely_being_run_by_virtualenv:
        this_must_be_run_by_the_virtualenv()
    else:
        create_virtualenv_if_it_does_not_exist()
        os.execv(python_executable, [python_executable, __file__, '--definitely-being-run-by-virtualenv'])
```
(Except `--definitely-being-run-by-virtualenv` is renamed to `--no-env` and the if-else is implicit rather than explicit.)

I mean, it'll work. It still seems really weird to me to have a file that recursively calls itself when we explicitly do not want any actual recursion to ever happen. That seems like it's just asking for bizarre bugs down the line.

**Comment by ionelmc** [comment]
Yes it's basically that mockup. I added the recursion/reexec thing into bootstrap.py just to be able to run with without tox. Why you ask? Because in some configuration tox.ini is generated and I really wanted to have an eas way to run bootstrap.py when tox.ini is completely broken.

**Comment by dHannasch** [comment]
It's good that you don't depend on tox, the whole bootstrapping business is a great idea, but I don't see the connection to recursion at all. If you didn't use recursion --- if you just called `create_virtualenv_if_it_does_not_exist()`, then called `this_must_be_run_by_the_virtualenv()` with the created virtualenv --- you still wouldn't depend on tox.

**Comment by ionelmc** [comment]
Yeah but then I have 1 extra file around.

**Comment by dHannasch** [comment]
(shrug) You do in fact have two different things that you need done, so...
In any case, like I said in https://github.com/ionelmc/cookiecutter-pylibrary/pull/139#issuecomment-534244647, if it bothers you to split the two functions across two files, they can be in one file explicitly `def`ed:
```
if __name__ == "__main__":
    create_virtualenv_if_it_does_not_exist()
    os.execv(python_executable, [python_executable, '-c', "import bootstrap; bootstrap.this_must_be_run_by_the_virtualenv()"])
```
Or at least make the command-line arguments into clear disjoint cases:
```
if __name__ == "__main__":
    if len(sys.argv[1:]) == 1:
        if sys.argv[1] == 'fill-templates':
            this_must_be_run_by_the_virtualenv()
        elif sys.argv[1] == 'create-env-and-fill-templates':
            python_executable = create_virtualenv_if_it_does_not_exist()
            os.execv(python_executable, [python_executable, __file__, 'fill-templates'])
        else: raise Exception
    else: raise Exception
```
Or if the full behavior must run with no command-line argument, then at least an explicit else-block:
```
if __name__ == "__main__":
    if len(sys.argv[1:]) == 1 and sys.argv[1] == 'fill-templates':
            this_must_be_run_by_the_virtualenv()
    elif len(sys.argv[:1]) == 0:
            python_executable = create_virtualenv_if_it_does_not_exist()
            os.execv(python_executable, [python_executable, __file__, 'fill-templates'])
    else: raise Exception
```

**Comment by ionelmc** [comment]
Mkay, fair points about the argv. I did some refactoring, how does it look?

**Comment by dHannasch** [comment]
Nice! I think the crucial `if __name__ == "__main__"` block is much easier to follow.

**Pull request merged**
